### ISSUE TITLE
As A Service version of coach corner

### ISSUE THREAD

**Issue by yvesgoeleven** [yvesgoeleven/BasketLummen#81]
Beide clubs

1. Ledenbeheer (belangrijkste): https://github.com/yvesgoeleven/BasketLummen/issues/3
- [ ] inclusief lijst alle ex-leden
- [ ] Bij Zolder ook mogelijkheid om per speler documenten up te loaden zoals evaluatieformulier

2.Inschrijving eetdagen 
- [x] Bij Lummen heb je dit al ontwikkeld (improve: https://github.com/yvesgoeleven/BasketLummen/issues/87)

3.Beheer toegang coach corner: https://github.com/yvesgoeleven/BasketLummen/issues/85
- [ ]  Bestuur kan volledige ledenlijst zien
- [ ]  Coach ziet bij ledenlijst alle namen en ploegen, maar enkel contactgegevens van zijn eigen ploeg en een ploeg jonger (vb U14 coach die U12ers kan contacteren om mee te trainen/spelen). Dit is omdat als je problemen krijgt met een coach en die vertrekt, hij niet alle contactgegevens kan meenemen. Is jaren geleden in Lummen gebeurd toen heeft één bepaalde coach alle leden een brief gestuurd om de club zwart te maken. -> Seperate management site for coaches
- [ ] Enkele beheerders kunnen dit aanpassen, vb aanduiden welke coach welke ploegen volledig mag bekijken.

Enkel Lummen
1. [ ] Sporhalbezetting https://github.com/yvesgoeleven/BasketLummen/issues/5
2. [x] Werklplan eetdagen https://github.com/yvesgoeleven/BasketLummen/issues/83
3. [ ] Topschutters Limburgse ploegen https://github.com/yvesgoeleven/BasketLummen/issues/84

Enkel Zolder
1. [ ] Beheer nieuwsberichten (niet meer nodig op site Lummen sinds nieuwe site) https://github.com/yvesgoeleven/BasketLummen/issues/88
2. [ ] Aanwezigheden op training (coaches en spelers), gekoppeld aan ledendatabase https://github.com/yvesgoeleven/BasketLummen/issues/8

**Comment by yvesgoeleven** [comment]
Moved https://github.com/MessageHandler/ClubManagement.Issues/issues/34
