### ISSUE TITLE
Team visualization

### ISSUE THREAD

**Issue by yvesgoeleven** [yvesgoeleven/BasketLummen#9]
## What is the problem?

* Players, coaches and parents need to know what team they are in.

## Discussion and conclusions

* Most of this data is available through VBL webservice (except G14 and younger)
* Existing website leverages the coach corner database instead, this data is not yet available for use in new website though.
* Not all teams are in our organization, there are collaboration teams with Zolder

## Plan of attack

- [x] Integrate VBL webservice to list teams in our organization
- [x] Integrate VBL webservice to list collaboration teams
- [x] Integrate VBL webservice to list team members
- [x] Integrate team list in website menu
   * [x] Dynamically during season transition period
   * [x] Static once season started and all teams are stable
- [x] Show team detail page
   * [x] Ensure every team has a team foto (https://github.com/MessageHandler/BasketLummen/issues/18)
   * [x] Ensure every person on the team has an individual foto (https://github.com/MessageHandler/BasketLummen/issues/18)
- [x] Ensure all these pages take teams outside of the organization into account (zolder collaboration)
- [x] Replace VBL webservice by organization service (https://github.com/MessageHandler/BasketLummen/issues/3)
